services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - POSTGRES_URL=postgresql://admin:123456@db-sql:5432/pattern_criteria_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pattern_criteria_db
    depends_on:
      - db-sql

  db-sql:
    build: ./flash-cards-database
    container_name: db-sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pattern_criteria_db
    volumes:
      - database-volume:/var/lib/postgresql/data

volumes:
  database-volume:
    driver: local
    driver_opts:
      type: none
      device: ./../database-volume
      o: bind
