INSERT INTO
    category (name)
VALUES ('Electronics'),
    ('Books'),
    ('Clothing'),
    ('Home & Kitchen'),
    ('Sports & Outdoors'),
    ('Toys & Games'),
    ('Health & Beauty'),
    ('Automotive'),
    ('Garden & Outdoors'),
    ('Office Supplies');

INSERT INTO brand (name) VALUES
('Electronics'),
('Apple'),
('Samsung'),
('Sony'),
('LG'),
('Dell'),
('HP'),
('Lenovo'),
('Microsoft'),
('Asus'),
('Acer'),
('Amazon'),
('Google'),
('Nike'),
('Adidas'),
('Puma'),
('Under Armour'),
('Levi\'s'),
('H&M'),
('Zara'),
('KitchenAid'),
('Philips'),
('Bosch'),
('Whirlpool'),
('Black+Decker'),
('Wilson'),
('Spalding'),
('Hasbro'),
('Mattel'),
('Johnson & Johnson');

INSERT INTO
    attribute (name)
VALUES ('Color'),
    ('Size'),
    ('Material'),
    ('Weight'),
    ('Dimensions'),
    ('Brand'),
    ('Model'),
    ('Price'),
    ('Warranty'),
    ('Origin'),
    ('SKU'),
    ('Manufacturer'),
    ('Expiration Date'),
    ('Capacity'),
    ('Quantity');

-- 100 random products
INSERT INTO
        product (
            name,
            description,
            price,
            rating,
            availability,
            brand_id,
            category_id
        )
    VALUES
        ('Bluetooth Speaker', 'Portable Bluetooth speaker with deep bass', 49.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Sony' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Electronics' LIMIT 1)),
        ('Yoga Mat', 'Non-slip yoga mat for fitness routines', 25.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Adidas' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Pressure Cooker', 'Stainless steel pressure cooker', 59.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Philips' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Wireless Mouse', 'Ergonomic wireless mouse', 19.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Logitech' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Electronics' LIMIT 1)),
        ('Water Bottle', 'Insulated water bottle for sports', 14.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Nike' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Cookbook', 'Healthy recipes for everyday cooking', 18.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Amazon' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Dress Shirt', 'Slim fit cotton dress shirt', 29.99, 4.2, TRUE, (SELECT uuid FROM brand WHERE name = 'Zara' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Clothing' LIMIT 1)),
        ('Vacuum Cleaner', 'Bagless vacuum cleaner with HEPA filter', 99.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Bosch' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Football', 'Durable football for outdoor play', 24.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Wilson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Board Book', 'Colorful board book for toddlers', 12.99, 4.9, TRUE, (SELECT uuid FROM brand WHERE name = 'Mattel' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Face Mask', 'Hydrating face mask for skincare', 7.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Car Charger', 'Fast charging USB car charger', 15.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Samsung' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Automotive' LIMIT 1)),
        ('Garden Gloves', 'Protective gloves for gardening', 9.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Bosch' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Garden & Outdoors' LIMIT 1)),
        ('Stapler', 'Heavy-duty office stapler', 8.99, 4.2, TRUE, (SELECT uuid FROM brand WHERE name = 'HP' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Office Supplies' LIMIT 1)),
        ('Puzzle Game', 'Challenging puzzle game for adults', 16.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Hasbro' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Toys & Games' LIMIT 1)),
        ('Lip Balm', 'Moisturizing lip balm', 3.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Tablet Stand', 'Adjustable stand for tablets', 13.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Lenovo' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Electronics' LIMIT 1)),
        ('Running Shorts', 'Lightweight running shorts', 19.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Puma' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Cookware Set', 'Non-stick cookware set', 79.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'KitchenAid' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Mystery Novel', 'Suspenseful mystery novel', 21.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Amazon' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Sweatshirt', 'Warm fleece sweatshirt', 24.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'H&M' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Clothing' LIMIT 1)),
        ('Toaster', '2-slice toaster with browning control', 29.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Philips' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Tennis Racket', 'Lightweight tennis racket', 59.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Wilson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Sticker Book', 'Fun sticker book for kids', 10.99, 4.9, TRUE, (SELECT uuid FROM brand WHERE name = 'Mattel' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Hand Sanitizer', 'Antibacterial hand sanitizer', 5.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Dash Cam', 'HD dash cam for vehicles', 69.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Sony' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Automotive' LIMIT 1)),
        ('Plant Pot', 'Ceramic plant pot for indoor plants', 14.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Bosch' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Garden & Outdoors' LIMIT 1)),
        ('Notebook', 'Spiral notebook for notes', 3.99, 4.2, TRUE, (SELECT uuid FROM brand WHERE name = 'HP' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Office Supplies' LIMIT 1)),
        ('Action Figure', 'Collectible action figure', 22.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Hasbro' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Toys & Games' LIMIT 1)),
        ('Shower Gel', 'Refreshing shower gel', 6.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Smart Plug', 'Wi-Fi enabled smart plug', 19.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Google' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Electronics' LIMIT 1)),
        ('Soccer Ball', 'Official size soccer ball', 25.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Adidas' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Rice Cooker', 'Automatic rice cooker', 39.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Philips' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Fantasy Novel', 'Epic fantasy adventure novel', 23.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Amazon' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Jacket', 'Water-resistant outdoor jacket', 59.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Levi\'s' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Clothing' LIMIT 1)),
        ('Coffee Grinder', 'Electric coffee grinder', 34.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'KitchenAid' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Jump Rope', 'Adjustable jump rope for workouts', 11.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Puma' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Coloring Book', 'Creative coloring book for adults', 13.99, 4.9, TRUE, (SELECT uuid FROM brand WHERE name = 'Mattel' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Body Lotion', 'Hydrating body lotion', 8.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Car Vacuum', 'Portable car vacuum cleaner', 29.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Black+Decker' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Automotive' LIMIT 1)),
        ('Garden Shears', 'Sharp garden shears for pruning', 17.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Bosch' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Garden & Outdoors' LIMIT 1)),
        ('Pen Set', 'Assorted color pen set', 5.99, 4.2, TRUE, (SELECT uuid FROM brand WHERE name = 'HP' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Office Supplies' LIMIT 1)),
        ('Board Puzzle', 'Wooden board puzzle for kids', 15.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Hasbro' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Toys & Games' LIMIT 1)),
        ('Face Wash', 'Gentle face wash for daily use', 7.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Fitness Tracker', 'Activity tracking fitness band', 49.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Samsung' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Electronics' LIMIT 1)),
        ('Basketball Shoes', 'High-top basketball shoes', 89.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Nike' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Slow Cooker', 'Programmable slow cooker', 44.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Whirlpool' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Romance Novel', 'Heartwarming romance novel', 19.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Amazon' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Sweatpants', 'Comfortable cotton sweatpants', 21.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'H&M' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Clothing' LIMIT 1)),
        ('Electric Kettle', 'Fast boiling electric kettle', 27.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Philips' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Golf Ball Set', 'Pack of 12 golf balls', 16.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Wilson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Picture Book', 'Beautiful picture book for children', 13.99, 4.9, TRUE, (SELECT uuid FROM brand WHERE name = 'Mattel' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Hair Conditioner', 'Nourishing hair conditioner', 6.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('GPS Navigator', 'Portable GPS navigation device', 89.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Garmin' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Automotive' LIMIT 1)),
        ('Garden Sprayer', 'Handheld garden sprayer', 19.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Bosch' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Garden & Outdoors' LIMIT 1)),
        ('File Organizer', 'Multi-section file organizer', 12.99, 4.2, TRUE, (SELECT uuid FROM brand WHERE name = 'HP' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Office Supplies' LIMIT 1)),
        ('Toy Car', 'Remote control toy car', 29.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Hasbro' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Toys & Games' LIMIT 1)),
        ('Sunscreen', 'SPF 50 sunscreen lotion', 9.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Smart Bulb', 'Color changing smart bulb', 14.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Google' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Electronics' LIMIT 1)),
        ('Yoga Block', 'Foam yoga block for support', 8.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Adidas' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Blender Bottle', 'Shaker bottle for smoothies', 11.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'KitchenAid' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Detective Novel', 'Classic detective mystery novel', 17.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Amazon' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Polo Shirt', 'Casual polo shirt', 18.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Zara' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Clothing' LIMIT 1)),
        ('Rice Cooker', 'Digital rice cooker', 49.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Philips' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Yoga Strap', 'Stretching yoga strap', 7.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Puma' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Sticker Album', 'Sticker album for collectors', 9.99, 4.9, TRUE, (SELECT uuid FROM brand WHERE name = 'Mattel' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Face Serum', 'Anti-aging face serum', 19.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Car Air Freshener', 'Long-lasting car air freshener', 4.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Black+Decker' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Automotive' LIMIT 1)),
        ('Garden Fork', 'Sturdy garden fork', 12.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Bosch' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Garden & Outdoors' LIMIT 1)),
        ('Desk Organizer', 'Desk organizer with drawers', 16.99, 4.2, TRUE, (SELECT uuid FROM brand WHERE name = 'HP' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Office Supplies' LIMIT 1)),
        ('Toy Train', 'Battery operated toy train', 24.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Hasbro' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Toys & Games' LIMIT 1)),
        ('Body Wash', 'Refreshing body wash', 7.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Smart Thermostat', 'Wi-Fi smart thermostat', 99.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Google' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Electronics' LIMIT 1)),
        ('Yoga Wheel', 'Yoga wheel for stretching', 21.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Adidas' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Food Processor', 'Multi-function food processor', 89.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'KitchenAid' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Adventure Novel', 'Exciting adventure novel', 20.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Amazon' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Denim Shorts', 'Classic denim shorts', 22.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Levi\'s' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Clothing' LIMIT 1)),
        ('Hand Mixer', 'Electric hand mixer', 29.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'KitchenAid' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Resistance Bands', 'Set of resistance bands', 14.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Puma' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Sticker Set', 'Assorted sticker set', 8.99, 4.9, TRUE, (SELECT uuid FROM brand WHERE name = 'Mattel' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Eye Cream', 'Revitalizing eye cream', 17.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Car Organizer', 'Multi-pocket car organizer', 18.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Black+Decker' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Automotive' LIMIT 1)),
        ('Garden Rake', 'Metal garden rake', 15.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Bosch' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Garden & Outdoors' LIMIT 1)),
        ('Staple Remover', 'Easy grip staple remover', 3.99, 4.2, TRUE, (SELECT uuid FROM brand WHERE name = 'HP' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Office Supplies' LIMIT 1)),
        ('Toy Blocks', 'Building blocks for kids', 19.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Hasbro' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Toys & Games' LIMIT 1)),
        ('Shaving Cream', 'Smooth shaving cream', 5.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Smart Lock', 'Keyless smart lock', 79.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Google' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Electronics' LIMIT 1)),
        ('Yoga Bag', 'Yoga mat carrying bag', 13.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Adidas' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Bread Maker', 'Automatic bread maker', 99.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'KitchenAid' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Historical Novel', 'Gripping historical novel', 22.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Amazon' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Winter Coat', 'Warm winter coat', 79.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Levi\'s' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Clothing' LIMIT 1)),
        ('Food Scale', 'Digital kitchen food scale', 19.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Philips' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Yoga Towel', 'Absorbent yoga towel', 11.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Puma' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Sticker Roll', 'Sticker roll for crafts', 6.99, 4.9, TRUE, (SELECT uuid FROM brand WHERE name = 'Mattel' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Night Cream', 'Rejuvenating night cream', 15.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Car Jump Starter', 'Portable car jump starter', 59.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Black+Decker' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Automotive' LIMIT 1)),
        ('Garden Hose Reel', 'Retractable garden hose reel', 39.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'Bosch' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Garden & Outdoors' LIMIT 1)),
        ('Desk Calendar', '2025 desk calendar', 7.99, 4.2, TRUE, (SELECT uuid FROM brand WHERE name = 'HP' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Office Supplies' LIMIT 1)),
        ('Toy Drum', 'Toy drum set for kids', 27.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Hasbro' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Toys & Games' LIMIT 1)),
        ('Hand Cream', 'Soothing hand cream', 6.99, 4.6, TRUE, (SELECT uuid FROM brand WHERE name = 'Johnson & Johnson' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Health & Beauty' LIMIT 1)),
        ('Smart Scale', 'Bluetooth smart body scale', 39.99, 4.3, TRUE, (SELECT uuid FROM brand WHERE name = 'Google' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Electronics' LIMIT 1)),
        ('Yoga Socks', 'Grip yoga socks', 7.99, 4.5, TRUE, (SELECT uuid FROM brand WHERE name = 'Adidas' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Sports & Outdoors' LIMIT 1)),
        ('Ice Cream Maker', 'Home ice cream maker', 59.99, 4.7, TRUE, (SELECT uuid FROM brand WHERE name = 'KitchenAid' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Home & Kitchen' LIMIT 1)),
        ('Science Book', 'Popular science book', 18.99, 4.8, TRUE, (SELECT uuid FROM brand WHERE name = 'Amazon' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Books' LIMIT 1)),
        ('Rain Jacket', 'Waterproof rain jacket', 39.99, 4.4, TRUE, (SELECT uuid FROM brand WHERE name = 'Levi\'s' LIMIT 1), (SELECT uuid FROM category WHERE name = 'Clothing' LIMIT 1));