### home
GET http://localhost:3000/api/

### Health Check
GET http://localhost:3000/api/health

### Get all
GET http://localhost:3000/api/products/v1

### Get by 
GET http://localhost:3000/api/products/v1?[0][field]=brandName&[0][operator]=EQUAL&[0][value]=Puma&orderBy=price&order=ASC

### pagination
GET http://localhost:3000/api/products/v1?&page=1&pageSize=2

###
GET http://localhost:3000/api/products/v1?%5B0%5D%5Bfield%5D=brandName&%5B0%5D%5Boperator%5D=EQUAL&%5B0%5D%5Bvalue%5D=Puma&%5B0%5D%5Bfield%5D=price&%5B0%5D%5Boperator%5D=LT&%5B0%5D%5Bvalue%5D=10


### 
GET http://localhost:3000/api/products/v1?%5B0%5D%5Bfield%5D=name&%5B0%5D%5Boperator%5D=CONTAINS&%5B0%5D%5Bvalue%5D=Travel&%5B0%5D%5Bfield%5D=price&%5B0%5D%5Boperator%5D=LT&%5B0%5D%5Bvalue%5D=10


### 
GET http://localhost:3000/api/products/v1?%5B0%5D%5Bfield%5D=name&%5B0%5D%5Boperator%5D=CONTAINS&%5B0%5D%5Bvalue%5D=Travel&%5B1%5D%5Bfield%5D=price&%5B1%5D%5Boperator%5D=GT&%5B1%5D%5Bvalue%5D=50


## Cursor-based Pagination

### 
GET http://localhost:3000/api/products/v1/cursor?&value=20